# -*- coding: utf-8 -*-
"""Breast Thermography.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtvqUvZaV39u8FRAx21O8fJVTdvtZ7G2
"""

!ls /content

!unzip -q "/content/Breast Thermography.zip" -d "/content/breast_thermography"

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

zip_path = "/content/Breast Thermography.zip"
extract_path = "/content/breast_thermography"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir(extract_path))

import os

BASE_DIR = "/content/breast_thermography/Breast Thermography"

print(os.listdir(BASE_DIR))

for root, dirs, files in os.walk(BASE_DIR):
    print(root, "| folders:", dirs[:5], "| files:", files[:5])

import os
import pandas as pd

BASE_DIR = "/content/breast_thermography/Breast Thermography"
CLASS_NAMES = ["Benign", "Malignant"]

filepaths = []
labels = []

for cls in CLASS_NAMES:
    class_dir = os.path.join(BASE_DIR, cls)
    print(f"Scanning: {class_dir}")

    for root, dirs, files in os.walk(class_dir):
        for fname in files:
            if fname.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff")):
                full_path = os.path.join(root, fname)
                filepaths.append(full_path)
                labels.append(cls)

data_df = pd.DataFrame({"filepath": filepaths, "label": labels})

print("Total images:", len(data_df))
print("\nLabel counts:")
print(data_df["label"].value_counts())
print("\nSample rows:")
print(data_df.head())

from PIL import Image
import matplotlib.pyplot as plt
import os

# Path to one benign folder
benign_path = "/content/breast_thermography/Breast Thermography/Benign/IIR0026"

# Get image names
images = os.listdir(benign_path)

print(images)

img = Image.open(os.path.join(benign_path, images[0]))

plt.figure(figsize=(6,6))
plt.imshow(img)
plt.axis('off')
plt.title("Benign Thermal Image")
plt.show()

malignant_path = "/content/breast_thermography/Breast Thermography/Malignant/IIR0046"

images = os.listdir(malignant_path)

print(images)

img = Image.open(os.path.join(malignant_path, images[0]))

plt.figure(figsize=(6,6))
plt.imshow(img)
plt.axis('off')
plt.title("Malignant Thermal Image")
plt.show()

print(data_df.head())
print(data_df.columns)
print(data_df.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
data_df["label"].value_counts().plot(kind="bar")
plt.title("Number of Images per Class")
plt.xlabel("Class")
plt.ylabel("Image Count")
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open(data_df["filepath"].iloc[0])
plt.imshow(img)
plt.axis("off")
plt.show()

from PIL import Image
import numpy as np

classes = data_df["label"].unique().tolist()
n_per_class = 4

plt.figure(figsize=(n_per_class*3, len(classes)*3))

idx = 1
for cls in classes:
    sample_rows = data_df[data_df["label"] == cls].sample(n=n_per_class, random_state=42)
    for _, row in sample_rows.iterrows():
        img = Image.open(row["filepath"])
        plt.subplot(len(classes), n_per_class, idx)
        plt.imshow(img, cmap="gray")
        plt.title(cls)
        plt.axis("off")
        idx += 1

plt.suptitle("Example Thermograms from Each Class", fontsize=14)
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    data_df,
    test_size=0.30,
    stratify=data_df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

print("\nDistribution:")
print("Train:\n", train_df["label"].value_counts())
print("\nVal:\n", val_df["label"].value_counts())
print("\nTest:\n", test_df["label"].value_counts())

split_names = ["Train", "Validation", "Test"]
dfs = [train_df, val_df, test_df]

counts = {
    "Split": [],
    "Class": [],
    "Count": []
}

for name, df in zip(split_names, dfs):
    vc = df["label"].value_counts()
    for cls, cnt in vc.items():
        counts["Split"].append(name)
        counts["Class"].append(cls)
        counts["Count"].append(cnt)

import pandas as pd
counts_df = pd.DataFrame(counts)

plt.figure(figsize=(7,4))
for cls in counts_df["Class"].unique():
    subset = counts_df[counts_df["Class"] == cls]
    plt.bar(subset["Split"], subset["Count"], alpha=0.7, label=cls)

plt.title("Images per Class in Train/Val/Test Splits")
plt.xlabel("Dataset Split")
plt.ylabel("Image Count")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.efficientnet import preprocess_input
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

IMG_SIZE = (224, 224)
BATCH_SIZE = 16

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=10,
    width_shift_range=0.05,
    height_shift_range=0.05,
    zoom_range=0.10,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_test_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

train_gen = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col="filepath",
    y_col="label",
    target_size=IMG_SIZE,
    class_mode="binary",
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_gen = val_test_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col="filepath",
    y_col="label",
    target_size=IMG_SIZE,
    class_mode="binary",
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_gen = val_test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col="filepath",
    y_col="label",
    target_size=IMG_SIZE,
    class_mode="binary",
    batch_size=BATCH_SIZE,
    shuffle=False
)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(train_gen.classes)
weights = compute_class_weight(class_weight="balanced", classes=classes, y=train_gen.classes)
class_weights = {int(c): float(w) for c, w in zip(classes, weights)}

print("Class indices:", train_gen.class_indices)
print("Class weights:", class_weights)

print(train_gen.class_indices)

print("Adjusted class weights:", class_weights)
print("Train counts:", np.bincount(train_gen.classes))
print("Class weights:", class_weights)

batch_images, batch_labels = next(train_gen)

import matplotlib.pyplot as plt
import numpy as np

def denormalize(img):
    img = img.copy()
    img -= img.min()
    img /= (img.max() + 1e-8)
    return img

plt.figure(figsize=(10,5))
for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(denormalize(batch_images[i]))
    plt.axis("off")
plt.show()

import tensorflow as tf
BACKBONES = {
    "EfficientNetB0": tf.keras.applications.EfficientNetB0,
    "ResNet50": tf.keras.applications.ResNet50,
    "DenseNet121": tf.keras.applications.DenseNet121,
    "InceptionV3": tf.keras.applications.InceptionV3,
}
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

def build_model(backbone_name, backbone_fn):
    base_model = backbone_fn(
        include_top=False,
        weights="imagenet",
        input_shape=(224, 224, 3)
    )

    base_model.trainable = False

    inputs = tf.keras.layers.Input(shape=(224, 224, 3))
    x = base_model(inputs, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model = tf.keras.Model(inputs, outputs, name=backbone_name)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
        loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="acc"),
            tf.keras.metrics.AUC(name="auc"),
            tf.keras.metrics.Recall(name="recall"),
            tf.keras.metrics.Precision(name="precision"),
        ]
    )

    return model, base_model

trained_models = {}

for name, backbone_fn in BACKBONES.items():
    print(f"\n==============================")
    print(f"Training model: {name}")
    print(f"==============================")

    model, base_model = build_model(name, backbone_fn)

    checkpoint_path = f"best_{name}.keras"

    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            checkpoint_path,
            monitor="val_loss",
            save_best_only=True,
            mode="min",
            verbose=1
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=8,
            restore_best_weights=True,
            mode="min",
            verbose=1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=3,
            min_lr=1e-7,
            verbose=1
        )
    ]

    model.fit(
        train_gen,
        validation_data=val_gen,
        epochs=25,
        callbacks=callbacks,
        class_weight=class_weights,
        verbose=1
    )

    base_model.trainable = True

    for layer in base_model.layers:
        if isinstance(layer, tf.keras.layers.BatchNormalization):
            layer.trainable = False

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=3e-6),
        loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="acc"),
            tf.keras.metrics.AUC(name="auc"),
            tf.keras.metrics.Recall(name="recall"),
            tf.keras.metrics.Precision(name="precision"),
        ]
    )

    model.fit(
        train_gen,
        validation_data=val_gen,
        epochs=15,
        callbacks=callbacks,
        class_weight=class_weights,
        verbose=1
    )

    best_model = tf.keras.models.load_model(checkpoint_path)
    trained_models[name] = best_model

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

results = []

y_true = test_gen.classes

for name, model in trained_models.items():
    print(f"\nEvaluating {name}")

    y_prob = model.predict(test_gen).ravel()
    y_pred = (y_prob >= 0.5).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Sensitivity": recall_score(y_true, y_pred, zero_division=0),
        "Specificity": tn / (tn + fp + 1e-8),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC_AUC": roc_auc_score(y_true, y_prob)
    })

results_df = pd.DataFrame(results)
results_df

all_probs = []

for name, model in trained_models.items():
    probs = model.predict(test_gen).ravel()
    all_probs.append(probs)

ensemble_prob = np.mean(all_probs, axis=0)
ensemble_pred = (ensemble_prob >= 0.5).astype(int)

tn, fp, fn, tp = confusion_matrix(y_true, ensemble_pred).ravel()

ensemble_results = {
    "Model": "Ensemble_SoftVoting",
    "Accuracy": accuracy_score(y_true, ensemble_pred),
    "Precision": precision_score(y_true, ensemble_pred, zero_division=0),
    "Sensitivity": recall_score(y_true, ensemble_pred, zero_division=0),
    "Specificity": tn / (tn + fp + 1e-8),
    "F1": f1_score(y_true, ensemble_pred, zero_division=0),
    "ROC_AUC": roc_auc_score(y_true, ensemble_prob)
}

results_df = pd.concat([results_df, pd.DataFrame([ensemble_results])], ignore_index=True)
results_df

for layer in best_model.layers:
    print(layer.name, layer.__class__.__name__)

base_model = best_model.layers[1]

for layer in base_model.layers[::-1]:
    if isinstance(layer, tf.keras.layers.Conv2D):
        print("Last conv layer:", layer.name)
        break

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image

def make_gradcam_heatmap(img_array, model, base_model, last_conv_layer_name):
    last_conv_layer = base_model.get_layer(last_conv_layer_name)

    grad_model = tf.keras.models.Model(
        inputs=model.inputs,
        outputs=[last_conv_layer.output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = predictions[:, 0]

    grads = tape.gradient(loss, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0) / (tf.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()

def load_image_for_gradcam(img_path):
    img = Image.open(img_path).convert("RGB")
    img = img.resize((224, 224))

    img_array = np.array(img)
    img_array = np.expand_dims(img_array, axis=0)

    # IMPORTANT: choose correct preprocess based on your model
    img_array = tf.keras.applications.densenet.preprocess_input(img_array)

    return img, img_array

y_prob = best_model.predict(test_gen).ravel()

high_conf_idx = np.argmax(y_prob)  # most confident malignant

sample_img_path = test_df.iloc[high_conf_idx]["filepath"]
original_img, img_array = load_image_for_gradcam(sample_img_path)

def make_gradcam_heatmap_nested(img_array, model, base_model, last_conv_layer_name):
    last_conv_layer = base_model.get_layer(last_conv_layer_name)

    conv_model = tf.keras.models.Model(
        inputs=base_model.input,
        outputs=[last_conv_layer.output, base_model.output]
    )

    classifier_layers = model.layers[2:]  # layers after backbone

    with tf.GradientTape() as tape:
        conv_outputs, x = conv_model(img_array)

        for layer in classifier_layers:
            x = layer(x)

        predictions = x
        loss = predictions[:, 0]

    grads = tape.gradient(loss, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0) / (tf.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()

def load_image_for_gradcam(img_path):
    img = Image.open(img_path).convert("RGB")
    img = img.resize((224, 224))

    img_array = np.array(img)
    img_array = np.expand_dims(img_array, axis=0)

    img_array = tf.keras.applications.inception_v3.preprocess_input(img_array)

    return img, img_array

import matplotlib.pyplot as plt
import numpy as np
import cv2

def display_gradcam(original_img, heatmap, alpha=0.4):
    img = np.array(original_img)

    heatmap_resized = cv2.resize(heatmap, (img.shape[1], img.shape[0]))
    heatmap_uint8 = np.uint8(255 * heatmap_resized)

    heatmap_color = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)

    superimposed_img = heatmap_color * alpha + img
    superimposed_img = np.uint8(superimposed_img)

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(img)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(heatmap_resized, cmap="jet")
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(superimposed_img)
    plt.title("Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

sample_img_path = test_df.iloc[0]["filepath"]
original_img, img_array = load_image_for_gradcam(sample_img_path)

last_conv_layer_name = "conv2d_93"
base_model = best_model.layers[1]

heatmap = make_gradcam_heatmap_nested(
    img_array,
    best_model,
    base_model,
    last_conv_layer_name
)

display_gradcam(original_img, heatmap)

def mask_important_region(original_img, heatmap, threshold=0.3):
    img = np.array(original_img)

    heatmap_resized = cv2.resize(heatmap, (img.shape[1], img.shape[0]))

    mask = heatmap_resized > threshold

    masked_img = img.copy()
    masked_img[mask] = 0  # remove important region

    return masked_img

def predict_image(img_array, model, preprocess_fn):
    img_array = preprocess_fn(img_array)
    prob = model.predict(img_array)[0][0]
    return prob

masked_img = mask_important_region(original_img, heatmap)

plt.figure(figsize=(6,3))

plt.subplot(1,2,1)
plt.imshow(original_img)
plt.title("Original")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(masked_img)
plt.title("Masked (important region removed)")
plt.axis("off")

plt.show()

preprocess_fn = tf.keras.applications.inception_v3.preprocess_input

# Original prediction
orig_array = np.expand_dims(np.array(original_img), axis=0)
orig_prob = predict_image(orig_array, best_model, preprocess_fn)

# Masked prediction
masked_array = np.expand_dims(masked_img, axis=0)
masked_prob = predict_image(masked_array, best_model, preprocess_fn)

print(f"Original Prediction: {orig_prob:.4f}")
print(f"Masked Prediction: {masked_prob:.4f}")
print(f"Confidence Drop: {orig_prob - masked_prob:.4f}")

drops = []

y_prob = best_model.predict(test_gen).ravel()

top_indices = np.argsort(y_prob)[-10:]  # top 10 confident

for idx in top_indices:
    sample_img_path = test_df.iloc[idx]["filepath"]

    original_img, img_array = load_image_for_gradcam(sample_img_path)

    heatmap = make_gradcam_heatmap_nested(
        img_array,
        best_model,
        best_model.layers[1],
        "conv2d_93"
    )

    masked_img = mask_important_region(original_img, heatmap, threshold=0.3)

    orig_array = np.expand_dims(np.array(original_img), axis=0)
    masked_array = np.expand_dims(masked_img, axis=0)

    orig_prob = predict_image(orig_array, best_model, preprocess_fn)
    masked_prob = predict_image(masked_array, best_model, preprocess_fn)

    drop = orig_prob - masked_prob
    drops.append(drop)

    print(f"Drop: {drop:.4f}")

print("\nAverage Drop:", np.mean(drops))

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

y_prob = best_model.predict(test_gen).ravel()
y_true = test_gen.classes

thresholds = np.linspace(0.0, 1.0, 100)

sensitivities = []
specificities = []

for t in thresholds:
    y_pred = (y_prob >= t).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    sensitivity = tp / (tp + fn + 1e-8)   # recall malignant
    specificity = tn / (tn + fp + 1e-8)   # true negative rate

    sensitivities.append(sensitivity)
    specificities.append(specificity)

plt.figure(figsize=(8,5))

plt.plot(thresholds, sensitivities, linewidth=2, label="Sensitivity")
plt.plot(thresholds, specificities, linewidth=2, label="Specificity")

# mark optimal threshold (optional)
optimal_idx = np.argmax(np.array(sensitivities) + np.array(specificities))
optimal_t = thresholds[optimal_idx]

plt.axvline(optimal_t, linestyle="--", label=f"Optimal Threshold = {optimal_t:.2f}")

plt.xlabel("Decision Threshold")
plt.ylabel("Score")
plt.title("Sensitivity–Specificity Tradeoff")

plt.legend()
plt.grid(True)

plt.savefig("sens_spec_curve_paper.png", dpi=300)
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score
import numpy as np

y_true = test_gen.classes

plt.figure(figsize=(8, 6))

for name, model in trained_models.items():
    y_prob = model.predict(test_gen).ravel()
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc_score = roc_auc_score(y_true, y_prob)

    plt.plot(fpr, tpr, linewidth=2, label=f"{name} AUC = {auc_score:.3f}")

# Ensemble ROC
fpr_ens, tpr_ens, _ = roc_curve(y_true, ensemble_prob)
auc_ens = roc_auc_score(y_true, ensemble_prob)

plt.plot(
    fpr_ens,
    tpr_ens,
    linewidth=3,
    linestyle="--",
    label=f"Ensemble AUC = {auc_ens:.3f}"
)

plt.plot([0, 1], [0, 1], linestyle=":", label="Random Classifier")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves for Individual CNN Backbones and Ensemble")
plt.legend()
plt.grid(True)
plt.savefig("roc_all_models_ensemble.png", dpi=300, bbox_inches="tight")
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score

plt.figure(figsize=(8, 6))

for name, model in trained_models.items():
    y_prob = model.predict(test_gen).ravel()
    precision, recall, _ = precision_recall_curve(y_true, y_prob)
    ap_score = average_precision_score(y_true, y_prob)

    plt.plot(recall, precision, linewidth=2, label=f"{name} AP = {ap_score:.3f}")

# Ensemble PR curve
precision_ens, recall_ens, _ = precision_recall_curve(y_true, ensemble_prob)
ap_ens = average_precision_score(y_true, ensemble_prob)

plt.plot(
    recall_ens,
    precision_ens,
    linewidth=3,
    linestyle="--",
    label=f"Ensemble AP = {ap_ens:.3f}"
)

plt.xlabel("Recall / Sensitivity")
plt.ylabel("Precision")
plt.title("Precision–Recall Curves for CNN Backbones and Ensemble")
plt.legend()
plt.grid(True)
plt.savefig("precision_recall_all_models_ensemble.png", dpi=300, bbox_inches="tight")
plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    average_precision_score
)

results = []

for name, model in trained_models.items():
    y_prob = model.predict(test_gen).ravel()
    y_pred = (y_prob >= 0.5).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    specificity = tn / (tn + fp + 1e-8)
    sensitivity = tp / (tp + fn + 1e-8)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Sensitivity": sensitivity,
        "Specificity": specificity,
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "F1-score": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "Average Precision": average_precision_score(y_true, y_prob),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    })

# Add ensemble
tn, fp, fn, tp = confusion_matrix(y_true, ensemble_pred).ravel()

results.append({
    "Model": "Soft Voting Ensemble",
    "Accuracy": accuracy_score(y_true, ensemble_pred),
    "Sensitivity": tp / (tp + fn + 1e-8),
    "Specificity": tn / (tn + fp + 1e-8),
    "Precision": precision_score(y_true, ensemble_pred, zero_division=0),
    "F1-score": f1_score(y_true, ensemble_pred, zero_division=0),
    "ROC-AUC": roc_auc_score(y_true, ensemble_prob),
    "Average Precision": average_precision_score(y_true, ensemble_prob),
    "TN": tn,
    "FP": fp,
    "FN": fn,
    "TP": tp
})

final_results_df = pd.DataFrame(results)

# round values for clean paper table
metric_cols = [
    "Accuracy", "Sensitivity", "Specificity",
    "Precision", "F1-score", "ROC-AUC", "Average Precision"
]

final_results_df[metric_cols] = final_results_df[metric_cols].round(4)

final_results_df

final_results_df.to_csv("final_model_comparison_table.csv", index=False)

fig, ax = plt.subplots(figsize=(14, 4))
ax.axis("off")

table = ax.table(
    cellText=final_results_df.values,
    colLabels=final_results_df.columns,
    cellLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(9)
table.scale(1, 1.5)

plt.title("Performance Comparison of CNN Backbones and Ensemble", fontsize=14)
plt.savefig("final_model_comparison_table.png", dpi=300, bbox_inches="tight")
plt.show()